### ISSUE TITLE
GPU is not used on Windows

### ISSUE THREAD

**Issue by antithing** [DefTruth/lite.ai.toolkit#290]
Hi, I am trying to run the Deeplab model for segmentation on Windows.

I have tried the ORT binaries, and also built it from source (including CUDA and cuDNN).
ENABLE_ONYXRUNTIME_CUDA is set.

I run the lite_deeplabv3_resnet101 example for ten images in a loop, and it takes 7 seconds for each frame on my machine (RTX 3090 GPU).

Looking at the task manager, the GPU is not used at all.

Am I missing something? What can I do to use CUDA with your code?

Thank you!

**Comment by antithing** [comment]
Hi! thanks for getting back to me. This has the same result. around 7 seconds a frame, and no GPU usage at all. Is there anything else i can try?

**Comment by antithing** [comment]
.. I would also like to try TNN to compare, but cannot access Baidu here, is there any way you can upload the TNN models to Google Drive? Thanks again

**Comment by antithing** [comment]
Hi @DefTruth , I have solved this by updating to the latest ORT and adjusting some code, but I am still hitting problems. If you have a minute, would you be able to show me how to convert the deeplabv3_mobilenet_v3_large_coco to onyx? Or resnet50?

Thank you very much!
